env_id: "blocks_stack_hard_mcts"
exe_num: 20
sample_num: 20
show_key_points: false
debug_key_frame: false
max_init_scene_num: 10   # Maximum number of steps to initialize the scene
# maniskill specific settings
obs_mode: null
reward_mode: null
control_mode: pd_joint_pos
render_mode: auto
shader: default # default, rt
num_envs: 1
sim_backend: auto
enable_shadow: true
parallel_in_single_scene: false

camera_config:
  L515:
    fovy: 54
    w: 960
    h: 540

  D435:
    fovy: 80
    w: 320
    h: 240

default:
  env_seed: 0         
  render_scene: false
  random_scene: true           
  random_once: true              
  record_data: false            
  calculate_success_rate: true
  # initialize scene step parameters
  init_scene: true  
  init_scene_step_num: 40
  # end scene step parameters
  end_scene: true
  end_scene_step_num: 20
  # 
  save_video: true
  save_when_fail: false
  record_env_name: ""            
  record_freq: 10                 
  pcd_crop: true                  
  head_camera_type: D435
  front_camera_type: L515
  pcd_down_sample_num: 1024