dataset_names: [
  blocks_stack_easy_20250703_031929_pkl,
] # base path: humanoidgen/datasets
episode_num: [0,100]
run_type: show_pc # show_video, save_video, show_pc, show_states
fps: 30
video_writer_type: "imageio" # "imageio" or "opencv" 